module.exports = Object.freeze({
  receive: { GET_ACCOUNTS: 'GET_ACCOUNTS' },
  emit: {
    GET_ACCOUNTS_SUCCESS: 'GET_ACCOUNTS_SUCCESS',
    GET_ACCOUNTS_FAILURE: 'GET_ACCOUNTS_FAILURE'
  },
  broadcast: {
    ACCOUNT_CREATED: 'ACCOUNT_CREATED',
    ACCOUNT_TAKEN: 'ACCOUNT_TAKEN'
  }
});
