const tests = [
  user => user,
  user => user.toLowerCase(),
  user => user.replace(/ /g, ''),
  user => user.replace(/ /g, '').toLowerCase(),
  _ => 'abc123',
  _ => 'wasd',
  _ => 'qwerty',
  _ => 'qwerty1',
  _ => 'qwerty12',
  _ => 'qwerty123',
  _ => 'qwerty1234',
  _ => '1234',
  _ => '12345678',
  _ => 'password',
  _ => 'password1',
  _ => 'dragon123',
  _ => 'iloveyou123',
  user => `${user}1`,
  user => `${user}12`,
  user => `${user}123`,
  user => `${user}1234`,
  user => `${user}12345678`,
  user => `${user.toLowerCase()}1`,
  user => `${user.toLowerCase()}12`,
  user => `${user.toLowerCase()}123`,
  user => `${user.toLowerCase()}1234`,
  user => `${user.toLowerCase()}12345678`,
  user => `${user.replace(/ /g, '')}1`,
  user => `${user.replace(/ /g, '')}12`,
  user => `${user.replace(/ /g, '')}123`,
  user => `${user.replace(/ /g, '')}1234`,
  user => `${user.replace(/ /g, '')}12345678`,
  user => user.replace(/ /g, '_'),
  user => `${user.replace(/ /g, '_')}1`,
  user => `${user.replace(/ /g, '_')}12`,
  user => `${user.replace(/ /g, '_')}123`,
  user => `${user.replace(/ /g, '_')}1234`,
  user => `${user.replace(/ /g, '_')}12345678`
];

const getPasswordSet = (userName = '') => [...new Set(tests.map(test => test(userName)))];

module.exports = { getPasswordSet };
